import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Tag from "../components/Tag";
import Footer from "@/components/Footer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#ffffff",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div
          className="bg-cover bg-center bg-no-repeat"
          style={{ backgroundImage: "url('/assets/images/pngs/bgsite.jpg')" }} // put your image in /public/bg.jpg
        >
          {/* Optional overlay for readability */}
          <div className="min-h-screen bg-black/30">
        {/* <Tag /> */}
        {/* <Header /> */}
        {children}
        <Footer />
        </div>
        </div>
      </body>
    </html>
  );
}
